import "./globals.css";

export const metadata = {
  title: "TodoPro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-[#F5F6F8]">{children}</body>
    </html>
  );
}
